# Generated by Django 2.0.2 on 2018-02-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('employer', models.CharField(max_length=200, verbose_name='Работодатель')),
                ('salary', models.CharField(max_length=200, verbose_name='Зарплатка')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Опыт')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['date', 'title'],
            },
        ),

    ]
