# Generated by Django 2.1 on 2018-02-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='description',
            new_name='content',
        ),
    ]
